version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    ports:
      - 3001:3000
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://172.22.63.118:3001
      - NEXT_PUBLIC_VIEWER_URL=http://172.22.63.118:3002

      - ENCRYPTION_SECRET=9bd08a339fb03237e02cb5ce0f430675

      - ADMIN_EMAIL=email@gmail.com

      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=email@gmail.com
      - SMTP_PASSWORD=senha
      - NEXT_PUBLIC_SMTP_FROM='Suporte Typebot' <email@gmail.com>

      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storagezdg.comunidadezdg.com.br
  typebot-viewer:
    ports:
      - 3002:3000
    image: baptistearno/typebot-viewer:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://172.22.63.118:3002
      - NEXTAUTH_URL=http://172.22.63.118:3001
      - ENCRYPTION_SECRET=9bd08a339fb03237e02cb5ce0f430675

      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storagezdg.comunidadezdg.com.br
  mail:
    image: bytemark/smtp
    restart: always
  minio:
    labels:
      virtual.host: 'storagezdg.comunidadezdg.com.br'
      virtual.port: '9000'
      virtual.tls-email: 'email@gmail.com'
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
volumes:
  db_data:
  s3_data: